### ISSUE TITLE
`readControl` doesn't set request direction correctly

### ISSUE THREAD

**Issue by mkeeter** [basvandijk/usb#13]
To construct the USB setup packet's `bmRequestType` byte, `readControl` uses `marshallControlSetup`, which in turn calls `marshalRequestType`.

Nothing in this function touches bit 7 of the `bmRequestType` byte, so the transfer is always sent out as a host-to-device transfer (rather than device-to-host), effectively writing rather than reading.

**Comment by basvandijk** [comment]
Fixed by #14.
