### ISSUE TITLE
cabal can't install usb or usb-safe, base issues

### ISSUE THREAD

**Issue by mf0hka** [basvandijk/usb#9]
what version of "base" work for this project? I have 4.6
(cabal newb here.) Also, where can I get a working version of base?

:~/$ cabal install usb-safe
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: usb-safe-0.14 (user goal)
next goal: base (dependency of usb-safe-0.14)
rejecting: base-4.6.0.1/installed-8aa... (conflict: usb-safe => base>=4 &&
<4.5)
rejecting: base-4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0,
4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0,
4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed instance)
Dependency tree exhaustively searched.

so then, I tried installing using verbose output:
pastebin.com/W1yUXVdL

I hope that helps.
I was able to install the usb library using $cabal install usb-1.2

**Comment by basvandijk** [comment]
Hi @mf0hka , The `usb-safe` library is currently unsupported. It should only build on old version of GHC that have base <= 4.6.

I recommend just using the `usb` library.
